"""initial schema

Revision ID: 92ebc94d52f6
Revises: 
Create Date: 2026-04-05 20:26:05.280603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ebc94d52f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('firm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('decision_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'firms', ['firm_id'], ['id'])

    with op.batch_alter_table('code_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiction', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_code_requirements_jurisdiction'), ['jurisdiction'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_requirements_jurisdiction'))
        batch_op.drop_column('jurisdiction')

    with op.batch_alter_table('assessment_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('decision_note')
        batch_op.drop_column('decision_by')
        batch_op.drop_column('decision_timestamp')
        batch_op.drop_column('decision')
        batch_op.drop_column('firm_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
